def convert_unit(unit_str):
    # Define a dictionary of known unit conversions
    conversion_dict = {
        'N/CM**2': ['Pa', 10000],
        '/SEC': ['1/s', 1],
        'Pascals': ['Pa', 1],
        'rad/sec': ['rad/s', 1],
        'Tesla**2': ['T^2', 1],
        'V/CM': ['V/m', 100],
        'N/CM3/SEC': ['N/(m**3*s)', 1e6],
        'WEBERS': ['Wb', 1],
        'V*s': ['Wb', 1],
        'Tesla*cm': ['T*m', 1e-1],
        'RAD/SEC': ['rad/s', 1],
        'CM': ['m', 0.01],
        'AMPS/CM2': ['A/m^2', 1e4],
        'TESLA/CM2': ['T', 1e4],
        'VOLT*TESLA/CM': ['V*T/m', 1e2],
        'GRAMS/CM3': ['kg/m^3', 1e3],
        'Tesla': ['T', 1],
        'T*(cm/sec)': ['T*(m/s)', 0.01],
        'N/SEC': ['N/s', 1],
        '#ptcls': ['', 1],
        'AMPS': ['A', 1],
        'N': ['N', 1],
        'Nt-M/CM3/(RAD/S)': ['kg/(m^3*s*rad)', 1000],
        'WATTS': ['W', 1],
        'eV': ['eV', 1.0],
        'CM**2/SEC': ['m^2/s', 1e-4],
        'CM**3': ['m**3', 1e-6],
        '1/SEC': ['1/s', 1],
        'ATOMS/SEC': ['ATOMS/SEC', 1],
        'CM**-1': ['m^-1', 1e2],
        'CM**-4': ['m^-4', 1e-8],
        'SECONDS': ['s', 1],
        '#/CM**3': ['#/m**3', 1e6],
        'W/cm**3': ['W/m^3', 1e6],
        'WATTS/CM3': ['W/m^3', 1e6],
        'NT-M': ['NT-M', 1],
        'TESLA*CM': ['T*m', 1e-2],
        'JLES/CM3': ['J/m^3', 1e6],
        'CM**2': ['m^2', 1e-4],
        'WATTS/CM3/EV': ['W/(m^3*eV)', 1e6],
        'EV': ['eV', 1.0],
        'AMP*TESLA/CM2': ['A*T/m^2',1e4]
    }
